export const COUNTRIES = [
  // ── AFRICA ──
  { name: "Algeria" }, { name: "Angola" }, { name: "Benin" },
  { name: "Botswana" }, { name: "Burkina Faso" }, { name: "Burundi" },
  { name: "Cameroon" }, { name: "Cape Verde" }, { name: "Central African Republic" },
  { name: "Chad" }, { name: "Comoros" }, { name: "Congo" },
  { name: "DR Congo" }, { name: "Djibouti" }, { name: "Egypt" },
  { name: "Equatorial Guinea" }, { name: "Eritrea" }, { name: "Eswatini" },
  { name: "Ethiopia" }, { name: "Gabon" }, { name: "Gambia" },
  { name: "Ghana" }, { name: "Guinea" }, { name: "Guinea-Bissau" },
  { name: "Ivory Coast" }, { name: "Kenya" }, { name: "Lesotho" },
  { name: "Liberia" }, { name: "Libya" }, { name: "Madagascar" },
  { name: "Malawi" }, { name: "Mali" }, { name: "Mauritania" },
  { name: "Mauritius" }, { name: "Morocco" }, { name: "Mozambique" },
  { name: "Namibia" }, { name: "Niger" }, { name: "Nigeria" },
  { name: "Rwanda" }, { name: "São Tomé & Príncipe" }, { name: "Senegal" },
  { name: "Seychelles" }, { name: "Sierra Leone" }, { name: "Somalia" },
  { name: "South Africa" }, { name: "South Sudan" }, { name: "Sudan" },
  { name: "Tanzania" }, { name: "Togo" }, { name: "Tunisia" },
  { name: "Uganda" }, { name: "Zambia" }, { name: "Zimbabwe" },

  // ── AMERICAS ──
  { name: "Antigua & Barbuda" }, { name: "Argentina" }, { name: "Bahamas" },
  { name: "Barbados" }, { name: "Belize" }, { name: "Bolivia" },
  { name: "Brazil" }, { name: "Canada" }, { name: "Chile" },
  { name: "Colombia" }, { name: "Costa Rica" }, { name: "Cuba" },
  { name: "Dominica" }, { name: "Dominican Republic" }, { name: "Ecuador" },
  { name: "El Salvador" }, { name: "Grenada" }, { name: "Guatemala" },
  { name: "Guyana" }, { name: "Haiti" }, { name: "Honduras" },
  { name: "Jamaica" }, { name: "Mexico" }, { name: "Nicaragua" },
  { name: "Panama" }, { name: "Paraguay" }, { name: "Peru" },
  { name: "Saint Kitts & Nevis" }, { name: "Saint Lucia" }, { name: "Saint Vincent" },
  { name: "Suriname" }, { name: "Trinidad & Tobago" }, { name: "United States" },
  { name: "Uruguay" }, { name: "Venezuela" },

  // ── ASIA ──
  { name: "Afghanistan" }, { name: "Armenia" }, { name: "Azerbaijan" },
  { name: "Bahrain" }, { name: "Bangladesh" }, { name: "Bhutan" },
  { name: "Brunei" }, { name: "Cambodia" }, { name: "China" },
  { name: "Georgia" }, { name: "India" }, { name: "Indonesia" },
  { name: "Iran" }, { name: "Iraq" }, { name: "Israel" },
  { name: "Japan" }, { name: "Jordan" }, { name: "Kazakhstan" },
  { name: "Kuwait" }, { name: "Kyrgyzstan" }, { name: "Laos" },
  { name: "Lebanon" }, { name: "Malaysia" }, { name: "Maldives" },
  { name: "Mongolia" }, { name: "Myanmar" }, { name: "Nepal" },
  { name: "North Korea" }, { name: "Oman" }, { name: "Pakistan" },
  { name: "Palestine" }, { name: "Philippines" }, { name: "Qatar" },
  { name: "Saudi Arabia" }, { name: "Singapore" }, { name: "South Korea" },
  { name: "Sri Lanka" }, { name: "Syria" }, { name: "Taiwan" },
  { name: "Tajikistan" }, { name: "Thailand" }, { name: "Timor-Leste" },
  { name: "Turkey" }, { name: "Turkmenistan" }, { name: "United Arab Emirates" },
  { name: "Uzbekistan" }, { name: "Vietnam" }, { name: "Yemen" },

  // ── EUROPE ──
  { name: "Albania" }, { name: "Andorra" }, { name: "Austria" },
  { name: "Belarus" }, { name: "Belgium" }, { name: "Bosnia & Herzegovina" },
  { name: "Bulgaria" }, { name: "Croatia" }, { name: "Cyprus" },
  { name: "Czech Republic" }, { name: "Denmark" }, { name: "Estonia" },
  { name: "Finland" }, { name: "France" }, { name: "Germany" },
  { name: "Greece" }, { name: "Hungary" }, { name: "Iceland" },
  { name: "Ireland" }, { name: "Italy" }, { name: "Kosovo" },
  { name: "Latvia" }, { name: "Liechtenstein" }, { name: "Lithuania" },
  { name: "Luxembourg" }, { name: "Malta" }, { name: "Moldova" },
  { name: "Monaco" }, { name: "Montenegro" }, { name: "Netherlands" },
  { name: "North Macedonia" }, { name: "Norway" }, { name: "Poland" },
  { name: "Portugal" }, { name: "Romania" }, { name: "Russia" },
  { name: "San Marino" }, { name: "Serbia" }, { name: "Slovakia" },
  { name: "Slovenia" }, { name: "Spain" }, { name: "Sweden" },
  { name: "Switzerland" }, { name: "Ukraine" }, { name: "United Kingdom" },
  { name: "Vatican City" },

  // ── OCEANIA ──
  { name: "Australia" }, { name: "Fiji" }, { name: "Kiribati" },
  { name: "Marshall Islands" }, { name: "Micronesia" }, { name: "Nauru" },
  { name: "New Zealand" }, { name: "Palau" }, { name: "Papua New Guinea" },
  { name: "Samoa" }, { name: "Solomon Islands" }, { name: "Tonga" },
  { name: "Tuvalu" }, { name: "Vanuatu" },
];
