export const COUNTRIES = [
  { name: "Afghanistan", flag: "🇦🇫" }, { name: "Albania", flag: "🇦🇱" },
  { name: "Algeria", flag: "🇩🇿" }, { name: "Argentina", flag: "🇦🇷" },
  { name: "Armenia", flag: "🇦🇲" }, { name: "Australia", flag: "🇦🇺" },
  { name: "Austria", flag: "🇦🇹" }, { name: "Azerbaijan", flag: "🇦🇿" },
  { name: "Bahrain", flag: "🇧🇭" }, { name: "Bangladesh", flag: "🇧🇩" },
  { name: "Belgium", flag: "🇧🇪" }, { name: "Bolivia", flag: "🇧🇴" },
  { name: "Bosnia & Herzegovina", flag: "🇧🇦" }, { name: "Brazil", flag: "🇧🇷" },
  { name: "Bulgaria", flag: "🇧🇬" }, { name: "Cambodia", flag: "🇰🇭" },
  { name: "Canada", flag: "🇨🇦" }, { name: "Chile", flag: "🇨🇱" },
  { name: "China", flag: "🇨🇳" }, { name: "Colombia", flag: "🇨🇴" },
  { name: "Croatia", flag: "🇭🇷" }, { name: "Cuba", flag: "🇨🇺" },
  { name: "Czech Republic", flag: "🇨🇿" }, { name: "Denmark", flag: "🇩🇰" },
  { name: "Ecuador", flag: "🇪🇨" }, { name: "Egypt", flag: "🇪🇬" },
  { name: "Estonia", flag: "🇪🇪" }, { name: "Ethiopia", flag: "🇪🇹" },
  { name: "Finland", flag: "🇫🇮" }, { name: "France", flag: "🇫🇷" },
  { name: "Georgia", flag: "🇬🇪" }, { name: "Germany", flag: "🇩🇪" },
  { name: "Ghana", flag: "🇬🇭" }, { name: "Greece", flag: "🇬🇷" },
  { name: "Guatemala", flag: "🇬🇹" }, { name: "Hungary", flag: "🇭🇺" },
  { name: "Iceland", flag: "🇮🇸" }, { name: "India", flag: "🇮🇳" },
  { name: "Indonesia", flag: "🇮🇩" }, { name: "Iran", flag: "🇮🇷" },
  { name: "Iraq", flag: "🇮🇶" }, { name: "Ireland", flag: "🇮🇪" },
  { name: "Israel", flag: "🇮🇱" }, { name: "Italy", flag: "🇮🇹" },
  { name: "Jamaica", flag: "🇯🇲" }, { name: "Japan", flag: "🇯🇵" },
  { name: "Jordan", flag: "🇯🇴" }, { name: "Kazakhstan", flag: "🇰🇿" },
  { name: "Kenya", flag: "🇰🇪" }, { name: "South Korea", flag: "🇰🇷" },
  { name: "Kuwait", flag: "🇰🇼" }, { name: "Laos", flag: "🇱🇦" },
  { name: "Latvia", flag: "🇱🇻" }, { name: "Lebanon", flag: "🇱🇧" },
  { name: "Lithuania", flag: "🇱🇹" }, { name: "Luxembourg", flag: "🇱🇺" },
  { name: "Malaysia", flag: "🇲🇾" }, { name: "Malta", flag: "🇲🇹" },
  { name: "Mexico", flag: "🇲🇽" }, { name: "Mongolia", flag: "🇲🇳" },
  { name: "Montenegro", flag: "🇲🇪" }, { name: "Morocco", flag: "🇲🇦" },
  { name: "Myanmar", flag: "🇲🇲" }, { name: "Nepal", flag: "🇳🇵" },
  { name: "Netherlands", flag: "🇳🇱" }, { name: "New Zealand", flag: "🇳🇿" },
  { name: "Nigeria", flag: "🇳🇬" }, { name: "Norway", flag: "🇳🇴" },
  { name: "Oman", flag: "🇴🇲" }, { name: "Pakistan", flag: "🇵🇰" },
  { name: "Panama", flag: "🇵🇦" }, { name: "Peru", flag: "🇵🇪" },
  { name: "Philippines", flag: "🇵🇭" }, { name: "Poland", flag: "🇵🇱" },
  { name: "Portugal", flag: "🇵🇹" }, { name: "Qatar", flag: "🇶🇦" },
  { name: "Romania", flag: "🇷🇴" }, { name: "Russia", flag: "🇷🇺" },
  { name: "Saudi Arabia", flag: "🇸🇦" }, { name: "Senegal", flag: "🇸🇳" },
  { name: "Serbia", flag: "🇷🇸" }, { name: "Singapore", flag: "🇸🇬" },
  { name: "Slovakia", flag: "🇸🇰" }, { name: "Slovenia", flag: "🇸🇮" },
  { name: "South Africa", flag: "🇿🇦" }, { name: "Spain", flag: "🇪🇸" },
  { name: "Sri Lanka", flag: "🇱🇰" }, { name: "Sweden", flag: "🇸🇪" },
  { name: "Switzerland", flag: "🇨🇭" }, { name: "Syria", flag: "🇸🇾" },
  { name: "Taiwan", flag: "🇹🇼" }, { name: "Tanzania", flag: "🇹🇿" },
  { name: "Thailand", flag: "🇹🇭" }, { name: "Tunisia", flag: "🇹🇳" },
  { name: "Turkey", flag: "🇹🇷" }, { name: "Uganda", flag: "🇺🇬" },
  { name: "Ukraine", flag: "🇺🇦" }, { name: "United Arab Emirates", flag: "🇦🇪" },
  { name: "United Kingdom", flag: "🇬🇧" }, { name: "United States", flag: "🇺🇸" },
  { name: "Uruguay", flag: "🇺🇾" }, { name: "Uzbekistan", flag: "🇺🇿" },
  { name: "Venezuela", flag: "🇻🇪" }, { name: "Vietnam", flag: "🇻🇳" },
  { name: "Yemen", flag: "🇾🇪" }, { name: "Zimbabwe", flag: "🇿🇼" },
];
